version: '3.8'

services:
  catalogue:
    build: ./catalogue
    ports:
      - "8081:8081"
    networks:
      - ecommerce-network

  commande:
    build: ./commande
    ports:
      - "8082:8082"
    networks:
      - ecommerce-network
    depends_on:
      - catalogue

networks:
  ecommerce-network:
    driver: bridge
